/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LearningMaterial {
    id: string;
    file: ExternalBlob;
    filename: string;
    subjectId: string;
    teacherPrincipal: Principal;
    uploadDate: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QuizQuestion {
    text: string;
    correctAnswer?: bigint;
    options: Array<string>;
}
export interface Quiz {
    title: string;
    duration: bigint;
    createdAt: bigint;
    subjectId: string;
    teacherPrincipal: Principal;
    questions: Array<QuizQuestion>;
    quizId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface QuizSubmission {
    answers: Array<bigint>;
    completed: boolean;
    studentPrincipal: Principal;
    score: bigint;
    timestamp: bigint;
    quizId: string;
}
export interface TeacherProfile {
    name: string;
    email: string;
    assignedSubjects: Array<string>;
    photo?: ExternalBlob;
    registrationDate: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface StudentProfile {
    grades: Array<[string, bigint]>;
    profileImage?: ExternalBlob;
    name: string;
    email: string;
    registrationDate: bigint;
    enrolledSubjects: Array<string>;
}
export interface AdminProfile {
    name: string;
    email: string;
}
export interface Subject {
    id: string;
    name: string;
    description: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignGrade(student: Principal, subjectId: string, grade: bigint): Promise<void>;
    assignSubjectToTeacher(teacher: Principal, subjectId: string): Promise<void>;
    createQuiz(quiz: Quiz): Promise<string>;
    enrollInSubject(subjectId: string): Promise<void>;
    getAdminProfile(user: Principal): Promise<AdminProfile | null>;
    getCallerAdminProfile(): Promise<AdminProfile | null>;
    getCallerStudentProfile(): Promise<StudentProfile | null>;
    getCallerTeacherProfile(): Promise<TeacherProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLearningMaterials(subjectId: string): Promise<Array<LearningMaterial>>;
    getMaterialDetails(materialId: string): Promise<LearningMaterial | null>;
    getMyQuizResults(): Promise<Array<QuizSubmission>>;
    getQuizDetails(quizId: string): Promise<Quiz | null>;
    getQuizSubmissionsForGrading(): Promise<Array<QuizSubmission>>;
    getQuizzesBySubject(subjectId: string): Promise<Array<Quiz>>;
    getStudentProfile(user: Principal): Promise<StudentProfile | null>;
    getStudentsInMySubjects(): Promise<Array<[Principal, StudentProfile]>>;
    getSubject(id: string): Promise<Subject | null>;
    getSubjects(): Promise<Array<Subject>>;
    getTeacherProfile(user: Principal): Promise<TeacherProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listAllStudents(): Promise<Array<[Principal, StudentProfile]>>;
    listAllTeachers(): Promise<Array<[Principal, TeacherProfile]>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveAdminProfile(profile: AdminProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    saveTeacherProfile(profile: TeacherProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitQuizAnswers(quizId: string, answers: Array<bigint>): Promise<void>;
    uploadLearningMaterial(subjectId: string, filename: string, file: ExternalBlob): Promise<string>;
}
import type { AdminProfile as _AdminProfile, ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, LearningMaterial as _LearningMaterial, Quiz as _Quiz, QuizQuestion as _QuizQuestion, StudentProfile as _StudentProfile, Subject as _Subject, TeacherProfile as _TeacherProfile, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignGrade(arg0: Principal, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignGrade(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignGrade(arg0, arg1, arg2);
            return result;
        }
    }
    async assignSubjectToTeacher(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSubjectToTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSubjectToTeacher(arg0, arg1);
            return result;
        }
    }
    async createQuiz(arg0: Quiz): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(to_candid_Quiz_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(to_candid_Quiz_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async enrollInSubject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInSubject(arg0);
            return result;
        }
    }
    async getAdminProfile(arg0: Principal): Promise<AdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminProfile(arg0);
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminProfile(arg0);
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerAdminProfile(): Promise<AdminProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAdminProfile();
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAdminProfile();
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerStudentProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStudentProfile();
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStudentProfile();
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerTeacherProfile(): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTeacherProfile();
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTeacherProfile();
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLearningMaterials(arg0: string): Promise<Array<LearningMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningMaterials(arg0);
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningMaterials(arg0);
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMaterialDetails(arg0: string): Promise<LearningMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialDetails(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialDetails(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyQuizResults(): Promise<Array<QuizSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizResults();
            return result;
        }
    }
    async getQuizDetails(arg0: string): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizDetails(arg0);
                return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizDetails(arg0);
            return from_candid_opt_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuizSubmissionsForGrading(): Promise<Array<QuizSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizSubmissionsForGrading();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizSubmissionsForGrading();
            return result;
        }
    }
    async getQuizzesBySubject(arg0: string): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzesBySubject(arg0);
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzesBySubject(arg0);
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudentProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudentsInMySubjects(): Promise<Array<[Principal, StudentProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsInMySubjects();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsInMySubjects();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSubject(arg0: string): Promise<Subject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubject(arg0);
                return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubject(arg0);
            return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async getTeacherProfile(arg0: Principal): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfile(arg0);
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfile(arg0);
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listAllStudents(): Promise<Array<[Principal, StudentProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudents();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudents();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async listAllTeachers(): Promise<Array<[Principal, TeacherProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTeachers();
                return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTeachers();
            return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveAdminProfile(arg0: AdminProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAdminProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAdminProfile(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(await to_candid_StudentProfile_n48(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(await to_candid_StudentProfile_n48(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveTeacherProfile(arg0: TeacherProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTeacherProfile(await to_candid_TeacherProfile_n51(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTeacherProfile(await to_candid_TeacherProfile_n51(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n53(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n53(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async submitQuizAnswers(arg0: string, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0, arg1);
            return result;
        }
    }
    async uploadLearningMaterial(arg0: string, arg1: string, arg2: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLearningMaterial(arg0, arg1, await to_candid_ExternalBlob_n50(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLearningMaterial(arg0, arg1, await to_candid_ExternalBlob_n50(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n47(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_LearningMaterial_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LearningMaterial): Promise<LearningMaterial> {
    return await from_candid_record_n29(uploadFile, downloadFile, value);
}
function from_candid_QuizQuestion_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestion): QuizQuestion {
    return from_candid_record_n36(uploadFile, downloadFile, value);
}
function from_candid_Quiz_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Quiz {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
async function from_candid_StudentProfile_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): Promise<StudentProfile> {
    return await from_candid_record_n18(uploadFile, downloadFile, value);
}
async function from_candid_TeacherProfile_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherProfile): Promise<TeacherProfile> {
    return await from_candid_record_n23(uploadFile, downloadFile, value);
}
function from_candid_UserApprovalInfo_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n45(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminProfile]): AdminProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): Promise<StudentProfile | null> {
    return value.length === 0 ? null : await from_candid_StudentProfile_n17(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherProfile]): Promise<TeacherProfile | null> {
    return value.length === 0 ? null : await from_candid_TeacherProfile_n22(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LearningMaterial]): Promise<LearningMaterial | null> {
    return value.length === 0 ? null : await from_candid_LearningMaterial_n28(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : from_candid_Quiz_n32(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subject]): Subject | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grades: Array<[string, bigint]>;
    profileImage: [] | [_ExternalBlob];
    name: string;
    email: string;
    registrationDate: bigint;
    enrolledSubjects: Array<string>;
}): Promise<{
    grades: Array<[string, bigint]>;
    profileImage?: ExternalBlob;
    name: string;
    email: string;
    registrationDate: bigint;
    enrolledSubjects: Array<string>;
}> {
    return {
        grades: value.grades,
        profileImage: record_opt_to_undefined(await from_candid_opt_n19(uploadFile, downloadFile, value.profileImage)),
        name: value.name,
        email: value.email,
        registrationDate: value.registrationDate,
        enrolledSubjects: value.enrolledSubjects
    };
}
async function from_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    assignedSubjects: Array<string>;
    photo: [] | [_ExternalBlob];
    registrationDate: bigint;
}): Promise<{
    name: string;
    email: string;
    assignedSubjects: Array<string>;
    photo?: ExternalBlob;
    registrationDate: bigint;
}> {
    return {
        name: value.name,
        email: value.email,
        assignedSubjects: value.assignedSubjects,
        photo: record_opt_to_undefined(await from_candid_opt_n19(uploadFile, downloadFile, value.photo)),
        registrationDate: value.registrationDate
    };
}
async function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    filename: string;
    subjectId: string;
    teacherPrincipal: Principal;
    uploadDate: bigint;
}): Promise<{
    id: string;
    file: ExternalBlob;
    filename: string;
    subjectId: string;
    teacherPrincipal: Principal;
    uploadDate: bigint;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n20(uploadFile, downloadFile, value.file),
        filename: value.filename,
        subjectId: value.subjectId,
        teacherPrincipal: value.teacherPrincipal,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    createdAt: bigint;
    subjectId: string;
    teacherPrincipal: Principal;
    questions: Array<_QuizQuestion>;
    quizId: string;
}): {
    title: string;
    duration: bigint;
    createdAt: bigint;
    subjectId: string;
    teacherPrincipal: Principal;
    questions: Array<QuizQuestion>;
    quizId: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        createdAt: value.createdAt,
        subjectId: value.subjectId,
        teacherPrincipal: value.teacherPrincipal,
        questions: from_candid_vec_n34(uploadFile, downloadFile, value.questions),
        quizId: value.quizId
    };
}
function from_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    correctAnswer: [] | [bigint];
    options: Array<string>;
}): {
    text: string;
    correctAnswer?: bigint;
    options: Array<string>;
} {
    return {
        text: value.text,
        correctAnswer: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.correctAnswer)),
        options: value.options
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n46(uploadFile, downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _StudentProfile]): Promise<[Principal, StudentProfile]> {
    return [
        value[0],
        await from_candid_StudentProfile_n17(uploadFile, downloadFile, value[1])
    ];
}
async function from_candid_tuple_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _TeacherProfile]): Promise<[Principal, TeacherProfile]> {
    return [
        value[0],
        await from_candid_TeacherProfile_n22(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LearningMaterial>): Promise<Array<LearningMaterial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LearningMaterial_n28(uploadFile, downloadFile, x)));
}
function from_candid_vec_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestion>): Array<QuizQuestion> {
    return value.map((x)=>from_candid_QuizQuestion_n35(uploadFile, downloadFile, x));
}
function from_candid_vec_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quiz>): Array<Quiz> {
    return value.map((x)=>from_candid_Quiz_n32(uploadFile, downloadFile, x));
}
async function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _StudentProfile]>): Promise<Array<[Principal, StudentProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n39(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _TeacherProfile]>): Promise<Array<[Principal, TeacherProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n42(uploadFile, downloadFile, x)));
}
function from_candid_vec_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n44(uploadFile, downloadFile, x));
}
function to_candid_ApprovalStatus_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n54(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_QuizQuestion_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizQuestion): _QuizQuestion {
    return to_candid_record_n14(uploadFile, downloadFile, value);
}
function to_candid_Quiz_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Quiz): _Quiz {
    return to_candid_record_n11(uploadFile, downloadFile, value);
}
async function to_candid_StudentProfile_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): Promise<_StudentProfile> {
    return await to_candid_record_n49(uploadFile, downloadFile, value);
}
async function to_candid_TeacherProfile_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherProfile): Promise<_TeacherProfile> {
    return await to_candid_record_n52(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    createdAt: bigint;
    subjectId: string;
    teacherPrincipal: Principal;
    questions: Array<QuizQuestion>;
    quizId: string;
}): {
    title: string;
    duration: bigint;
    createdAt: bigint;
    subjectId: string;
    teacherPrincipal: Principal;
    questions: Array<_QuizQuestion>;
    quizId: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        createdAt: value.createdAt,
        subjectId: value.subjectId,
        teacherPrincipal: value.teacherPrincipal,
        questions: to_candid_vec_n12(uploadFile, downloadFile, value.questions),
        quizId: value.quizId
    };
}
function to_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    correctAnswer?: bigint;
    options: Array<string>;
}): {
    text: string;
    correctAnswer: [] | [bigint];
    options: Array<string>;
} {
    return {
        text: value.text,
        correctAnswer: value.correctAnswer ? candid_some(value.correctAnswer) : candid_none(),
        options: value.options
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grades: Array<[string, bigint]>;
    profileImage?: ExternalBlob;
    name: string;
    email: string;
    registrationDate: bigint;
    enrolledSubjects: Array<string>;
}): Promise<{
    grades: Array<[string, bigint]>;
    profileImage: [] | [_ExternalBlob];
    name: string;
    email: string;
    registrationDate: bigint;
    enrolledSubjects: Array<string>;
}> {
    return {
        grades: value.grades,
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n50(uploadFile, downloadFile, value.profileImage)) : candid_none(),
        name: value.name,
        email: value.email,
        registrationDate: value.registrationDate,
        enrolledSubjects: value.enrolledSubjects
    };
}
async function to_candid_record_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    assignedSubjects: Array<string>;
    photo?: ExternalBlob;
    registrationDate: bigint;
}): Promise<{
    name: string;
    email: string;
    assignedSubjects: Array<string>;
    photo: [] | [_ExternalBlob];
    registrationDate: bigint;
}> {
    return {
        name: value.name,
        email: value.email,
        assignedSubjects: value.assignedSubjects,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n50(uploadFile, downloadFile, value.photo)) : candid_none(),
        registrationDate: value.registrationDate
    };
}
function to_candid_variant_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<QuizQuestion>): Array<_QuizQuestion> {
    return value.map((x)=>to_candid_QuizQuestion_n13(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
