/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizQuestion = IDL.Record({
  'text' : IDL.Text,
  'correctAnswer' : IDL.Opt(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'createdAt' : IDL.Int,
  'subjectId' : IDL.Text,
  'teacherPrincipal' : IDL.Principal,
  'questions' : IDL.Vec(QuizQuestion),
  'quizId' : IDL.Text,
});
export const AdminProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudentProfile = IDL.Record({
  'grades' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'registrationDate' : IDL.Int,
  'enrolledSubjects' : IDL.Vec(IDL.Text),
});
export const TeacherProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'assignedSubjects' : IDL.Vec(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
  'registrationDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LearningMaterial = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'filename' : IDL.Text,
  'subjectId' : IDL.Text,
  'teacherPrincipal' : IDL.Principal,
  'uploadDate' : IDL.Int,
});
export const QuizSubmission = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'completed' : IDL.Bool,
  'studentPrincipal' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quizId' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignGrade' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
  'assignSubjectToTeacher' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createQuiz' : IDL.Func([Quiz], [IDL.Text], []),
  'enrollInSubject' : IDL.Func([IDL.Text], [], []),
  'getAdminProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AdminProfile)],
      ['query'],
    ),
  'getCallerAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
  'getCallerStudentProfile' : IDL.Func(
      [],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getCallerTeacherProfile' : IDL.Func(
      [],
      [IDL.Opt(TeacherProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLearningMaterials' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LearningMaterial)],
      ['query'],
    ),
  'getMaterialDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LearningMaterial)],
      ['query'],
    ),
  'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizSubmission)], ['query']),
  'getQuizDetails' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
  'getQuizSubmissionsForGrading' : IDL.Func(
      [],
      [IDL.Vec(QuizSubmission)],
      ['query'],
    ),
  'getQuizzesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getStudentsInMySubjects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
      ['query'],
    ),
  'getSubject' : IDL.Func([IDL.Text], [IDL.Opt(Subject)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTeacherProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TeacherProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStudents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
      ['query'],
    ),
  'listAllTeachers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, TeacherProfile))],
      ['query'],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveAdminProfile' : IDL.Func([AdminProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'saveTeacherProfile' : IDL.Func([TeacherProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitQuizAnswers' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [], []),
  'uploadLearningMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizQuestion = IDL.Record({
    'text' : IDL.Text,
    'correctAnswer' : IDL.Opt(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'createdAt' : IDL.Int,
    'subjectId' : IDL.Text,
    'teacherPrincipal' : IDL.Principal,
    'questions' : IDL.Vec(QuizQuestion),
    'quizId' : IDL.Text,
  });
  const AdminProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudentProfile = IDL.Record({
    'grades' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'registrationDate' : IDL.Int,
    'enrolledSubjects' : IDL.Vec(IDL.Text),
  });
  const TeacherProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'assignedSubjects' : IDL.Vec(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
    'registrationDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LearningMaterial = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'filename' : IDL.Text,
    'subjectId' : IDL.Text,
    'teacherPrincipal' : IDL.Principal,
    'uploadDate' : IDL.Int,
  });
  const QuizSubmission = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'completed' : IDL.Bool,
    'studentPrincipal' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quizId' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignGrade' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
    'assignSubjectToTeacher' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createQuiz' : IDL.Func([Quiz], [IDL.Text], []),
    'enrollInSubject' : IDL.Func([IDL.Text], [], []),
    'getAdminProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AdminProfile)],
        ['query'],
      ),
    'getCallerAdminProfile' : IDL.Func([], [IDL.Opt(AdminProfile)], ['query']),
    'getCallerStudentProfile' : IDL.Func(
        [],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getCallerTeacherProfile' : IDL.Func(
        [],
        [IDL.Opt(TeacherProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLearningMaterials' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LearningMaterial)],
        ['query'],
      ),
    'getMaterialDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LearningMaterial)],
        ['query'],
      ),
    'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizSubmission)], ['query']),
    'getQuizDetails' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
    'getQuizSubmissionsForGrading' : IDL.Func(
        [],
        [IDL.Vec(QuizSubmission)],
        ['query'],
      ),
    'getQuizzesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentsInMySubjects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Text], [IDL.Opt(Subject)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTeacherProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TeacherProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStudents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
        ['query'],
      ),
    'listAllTeachers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, TeacherProfile))],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveAdminProfile' : IDL.Func([AdminProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'saveTeacherProfile' : IDL.Func([TeacherProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitQuizAnswers' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [], []),
    'uploadLearningMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };