/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminProfile { 'name' : string, 'email' : string }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface LearningMaterial {
  'id' : string,
  'file' : ExternalBlob,
  'filename' : string,
  'subjectId' : string,
  'teacherPrincipal' : Principal,
  'uploadDate' : bigint,
}
export interface Quiz {
  'title' : string,
  'duration' : bigint,
  'createdAt' : bigint,
  'subjectId' : string,
  'teacherPrincipal' : Principal,
  'questions' : Array<QuizQuestion>,
  'quizId' : string,
}
export interface QuizQuestion {
  'text' : string,
  'correctAnswer' : [] | [bigint],
  'options' : Array<string>,
}
export interface QuizSubmission {
  'answers' : Array<bigint>,
  'completed' : boolean,
  'studentPrincipal' : Principal,
  'score' : bigint,
  'timestamp' : bigint,
  'quizId' : string,
}
export interface StudentProfile {
  'grades' : Array<[string, bigint]>,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'email' : string,
  'registrationDate' : bigint,
  'enrolledSubjects' : Array<string>,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface TeacherProfile {
  'name' : string,
  'email' : string,
  'assignedSubjects' : Array<string>,
  'photo' : [] | [ExternalBlob],
  'registrationDate' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignGrade' : ActorMethod<[Principal, string, bigint], undefined>,
  'assignSubjectToTeacher' : ActorMethod<[Principal, string], undefined>,
  'createQuiz' : ActorMethod<[Quiz], string>,
  'enrollInSubject' : ActorMethod<[string], undefined>,
  'getAdminProfile' : ActorMethod<[Principal], [] | [AdminProfile]>,
  'getCallerAdminProfile' : ActorMethod<[], [] | [AdminProfile]>,
  'getCallerStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerTeacherProfile' : ActorMethod<[], [] | [TeacherProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLearningMaterials' : ActorMethod<[string], Array<LearningMaterial>>,
  'getMaterialDetails' : ActorMethod<[string], [] | [LearningMaterial]>,
  'getMyQuizResults' : ActorMethod<[], Array<QuizSubmission>>,
  'getQuizDetails' : ActorMethod<[string], [] | [Quiz]>,
  'getQuizSubmissionsForGrading' : ActorMethod<[], Array<QuizSubmission>>,
  'getQuizzesBySubject' : ActorMethod<[string], Array<Quiz>>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getStudentsInMySubjects' : ActorMethod<
    [],
    Array<[Principal, StudentProfile]>
  >,
  'getSubject' : ActorMethod<[string], [] | [Subject]>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTeacherProfile' : ActorMethod<[Principal], [] | [TeacherProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAllStudents' : ActorMethod<[], Array<[Principal, StudentProfile]>>,
  'listAllTeachers' : ActorMethod<[], Array<[Principal, TeacherProfile]>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveAdminProfile' : ActorMethod<[AdminProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'saveTeacherProfile' : ActorMethod<[TeacherProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitQuizAnswers' : ActorMethod<[string, Array<bigint>], undefined>,
  'uploadLearningMaterial' : ActorMethod<
    [string, string, ExternalBlob],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];